### ISSUE TITLE
Invalid state Error when unittesting

### ISSUE THREAD

**Issue by salztorte** [OnsenUI/react-onsenui#166]
Hey,
i use OnsenUi for my react projekt and i want testing it with jest.

When i start the test Osen throw an Error: 
```
Invalid state
      at node_modules\onsenui\js\onsenui.js:581:11
      at node_modules\onsenui\js\onsenui.js:582:5
      at Object.<anonymous> (node_modules\onsenui\js\onsenui.js:971:3)
      at Object.<anonymous>.React (node_modules\react-onsenui\dist\react-onsenui.js:3:123)
      at Object.<anonymous> (node_modules\react-onsenui\dist\react-onsenui.js:6:2)
      at Object.<anonymous> (src\Components\Footer\Footer.jsx:2:47)
      at Object.<anonymous> (src\Components\Footer\Footer.spec.js:5:41)
      at process._tickCallback (internal\process\next_tick.js:103:7)

```
So the funny thing is that the error comes already when i import the component and dont render it.

Footer.jsx
```
import { PropTypes } from 'react';
import { BottomToolbar } from 'react-onsenui';

const Footer = () => (
    <BottomToolbar modifier="material" />
);

Footer.propTypes = {};
export default Footer;
```

Footer.spec.js
```
import Footer from './Footer.jsx';

describe('Footer', () => {
    it('fuu', () => {
        expect(1).toBe(1);
    });

});
```

**Comment by salztorte** [comment]
I tried mocha & chai  out but still the same Problem with the invalid state.

I don't figure out where and why onsen throw this error when i testing.

Can someone help me pls?

**Comment by argelius** [comment]
@salztorte Could you set up a simple repo that reproduces this issue?

**Comment by salztorte** [comment]
@argelius  https://github.com/salztorte/OsenuiTestError
here is a simpel one.

**Comment by mcku** [comment]
I am facing the same issue as well. 

```
import Ons = require('react-onsenui')
```
when processed by jest, results in:
```
Invalid state
      
      at node_modules/onsenui/js/ons/animit.js:207:9
      at node_modules/onsenui/js/ons/animit.js:198:31
      at node_modules/onsenui/js/onsenui.js:3739:84
      at Object.<anonymous> (node_modules/onsenui/js/onsenui.js:3742:2)
      at React (node_modules/react-onsenui/dist/react-onsenui.js:3:123)
      at Object.<anonymous> (node_modules/react-onsenui/dist/react-onsenui.js:6:2)
```

`    "react-onsenui": "0.7.8", `

**Comment by dagatsoin** [comment]
Same here
```
Invalid state
      
      at ../../node_modules/onsenui/js/onsenui.js:4744:9
      at ../../node_modules/onsenui/js/onsenui.js:4745:2
      at ../../node_modules/onsenui/js/onsenui.js:3739:84
      at Object.<anonymous> (../../node_modules/onsenui/js/onsenui.js:3742:2)
      at Object.<anonymous>.React (../../node_modules/react-onsenui/dist/react-onsenui.js:3:123)
      at Object.<anonymous> (../../node_modules/react-onsenui/dist/react-onsenui.js:6:2)
      at Object.<anonymous> (1-molecules/LoadingBar.jsx:5:21)
      at Object.<anonymous> (1-molecules/LoadingBar.snapshot.test.jsx:2:19)
      at process._tickCallback (../../internal/process/next_tick.js:103:7)
```

**Comment by mcku** [comment]
This is likely because that `jsdom` does not faclilitate animations or css transitions. We should get around animations, perhaps by mocking. Or maybe by enzyme shallow rendering instead of full mount, I don't know. It would be nice if animations could be skipped just for unit tests.

After looking at animit.js, below is what jsdom provides as a result of `window.getComputedStyles` (for the curious, Chrome offers a few hundred, as expected). `dict` is supposed to contain something like `transitionDuration` for a good run without exceptions, but jsdom has none. 

```
 console.log node_modules/onsenui/js/onsenui.js:6510
    styles: {"_values":{},"_importants":{"scroll-blocks-on":""},"_length":0,"scrollBlocksOn":"start-touch wheel-event"}

  console.log node_modules/onsenui/js/onsenui.js:6521
    dict: {}
```

**Comment by frandiox** [comment]
@mcku I think it is possible to avoid the `Invalid state` error from the tests by applying a very dirty fix. However, I'm not sure if something else related to animations will fail.

Can you try something like this in your tests just to check?
```
Object.defineProperty(Object.prototype, 'transitionDuration', { value: 'very-dirty-fix'});
```

In Jest, for example, this should run in `setupTestFrameworkScriptFile`.

Pinging @anatoo here.

**Comment by mcku** [comment]
@frandiox  It looks like there are a lot steps to take. In this [SO](http://stackoverflow.com/questions/39843192/react-onsenui-mocha-test-error-error-invalid-state) post many of them are listed. 
In addition some of them are related to `document-register-element`. I have noticed `document-register-element/pony`, which no longer detects user agent (previously jsdom was being detected as IE8), and used it. 

So current situation is, failure to read attributes of an element, something to do with `document-register-element/pony` maybe, I don't know. 

```
console.log node_modules/onsenui/js/onsenui.js:6513
    styles: ["transitionDuration"]

  console.log node_modules/onsenui/js/onsenui.js:6524
    dict: {"transitionDuration":true}

  console.log node_modules/jsdom/lib/jsdom/living/generated/Element.js:461
    ToolbarElement { setAttribute: [Function: patchedSetAttribute] }
```

```
TypeError: Cannot read property 'attributes' of undefined
      
      at ToolbarElement.get [as attributes] (node_modules/jsdom/lib/jsdom/living/generated/Element.js:462:46)
      at getAttributesMirror (node_modules/document-register-element/pony/index.js:872:30)
      at setupNode (node_modules/document-register-element/pony/index.js:1159:29)
      at CustomElementsV1.patchedCreateElement (node_modules/document-register-element/pony/index.js:1037:18)
      at CustomElementsV1.document.createElement (node_modules/document-register-element/pony/index.js:1393:30)
      at CustomElementsV1.document.createElement (node_modules/onsenui/js/document-register-element.max.js:1387:1)
      at node_modules/onsenui/js/onsenui.js:19610:35
      at Object.<anonymous>._typeof (node_modules/onsenui/js/onsenui.js:3741:84)
      at Object.<anonymous> (node_modules/onsenui/js/onsenui.js:3744:2)
```
